# Generated by Django 6.0.8 on 2026-09-05 20:10

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_price_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('reference', models.CharField(blank=True, max_length=20, verbose_name='référence')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('REFUSED', 'Refusée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='statut')),
                ('total_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XAF', 'XAF')], default='XAF', editable=False, max_length=3)),
                ('total_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='montant total')),
                ('pickup_location', models.CharField(blank=True, max_length=255, verbose_name='lieu de remise')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='date de remise')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='heure de remise')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de confirmation')),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='date limite de confirmation')),
                ('auto_confirmation', models.BooleanField(default=False, verbose_name='confirmation automatique')),
                ('buyer', models.ForeignKey(limit_choices_to={'is_buyer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orders_placed', to=settings.AUTH_USER_MODEL, verbose_name='acheteur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('producer', models.ForeignKey(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orders_received', to=settings.AUTH_USER_MODEL, verbose_name='producteur')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantité')),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XAF', 'XAF')], default='XAF', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product', verbose_name='produit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['producer', 'status'], name='orders_orde_produce_7a0db6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='orders_orde_buyer_i_4389c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('reference',), name='uniq_order_reference_active'),
        ),
    ]
