# Generated by Django 6.0.8 on 2026-09-05 14:43

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XAF', 'XAF')], default='XAF', editable=False, max_length=3),
        ),
    ]
