# Generated by Django 6.0.8 on 2026-08-26 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email concerné')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGIN_LOCKED', 'Compte temporairement bloqué (brute-force)'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('PASSWORD_RESET_REQUESTED', 'Réinitialisation demandée'), ('PASSWORD_RESET_COMPLETED', 'Réinitialisation effectuée'), ('OTP_REQUESTED', 'Code OTP demandé'), ('OTP_VERIFIED', 'Code OTP vérifié'), ('OTP_FAILED', 'Échec de vérification OTP'), ('OTP_RATE_LIMITED', 'Demande OTP bloquée (anti-spam)'), ('SIGNUP', 'Inscription'), ('PRODUCER_APPROVED', 'Compte producteur approuvé'), ('PRODUCER_REJECTED', 'Compte producteur rejeté'), ('ACCOUNT_SUSPENDED', 'Compte suspendu'), ('ACCOUNT_REACTIVATED', 'Compte réactivé')], max_length=40, verbose_name="type d'événement")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
            ],
            options={
                'verbose_name': 'événement de sécurité',
                'verbose_name_plural': 'événements de sécurité',
                'ordering': ['-created_at'],
            },
        ),
    ]
