# Generated by Django 6.0.8 on 2026-09-26 13:53

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('fraud', 'Fraud')], db_index=True, default='pending', max_length=25, verbose_name='statut')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XAF', 'XAF')], default='XAF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('refunded_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XAF', 'XAF')], default='XAF', editable=False, max_length=3)),
                ('refunded_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'XAF'), max_digits=12, verbose_name='montant remboursé')),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Bank Card')], max_length=20, verbose_name='moyen de paiement')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe (Card)'), ('flutterwave_mobile_money', 'Flutterwave Mobile Money'), ('mobile_money_manual', 'Mobile Money (non configuré)')], help_text='Exemple : Stripe, Flutterwave, MTN, Orange.', max_length=50, verbose_name='fournisseur de paiement')),
                ('provider_reference', models.CharField(blank=True, help_text='Référence utilisée pour identifier la transaction auprès du fournisseur.', max_length=200, verbose_name='référence fournisseur')),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='Identifiant de transaction fourni par le prestataire de paiement.', max_length=200, verbose_name='ID de transaction fournisseur')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Réponse brute retournée par le fournisseur de paiement.', verbose_name='réponse du fournisseur')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'initiation")),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('failure_reason', models.TextField(blank=True, verbose_name="motif d'échec")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order', verbose_name='commande')),
                ('parent', models.ForeignKey(blank=True, help_text="Référence à la transaction d'origine pour les remboursements ou annulations.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='payments.paymenttransaction', verbose_name='transaction parente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'transaction de paiement',
                'verbose_name_plural': 'transactions de paiement',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='uniq_payment_provider_transaction_id')],
            },
        ),
    ]
