# Generated by Django 6.0.8 on 2026-08-26 22:55

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import farmio.users.managers
import farmio.utils.phone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[farmio.utils.phone.validate_phone_number], verbose_name='numéro de téléphone')),
                ('is_producer', models.BooleanField(default=False, verbose_name='est producteur')),
                ('is_buyer', models.BooleanField(default=True, verbose_name='est acheteur')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email vérifié')),
                ('is_approved', models.BooleanField(default=False, help_text='Requis pour que les producteurs puissent vendre sur la plateforme.', verbose_name="approuvé par l'admin")),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='ID client Stripe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', farmio.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('organization_name', models.CharField(blank=True, max_length=150, verbose_name='nom de la structure (optionnel)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.OneToOneField(limit_choices_to={'is_buyer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil acheteur',
                'verbose_name_plural': 'profils acheteurs',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('country', django_countries.fields.CountryField(default='CM', max_length=2, verbose_name='pays')),
                ('region', models.CharField(max_length=100, verbose_name='région')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'localisation',
                'verbose_name_plural': 'localisations',
                'unique_together': {('country', 'region', 'city')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.location', verbose_name='localisation'),
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('company_name', models.CharField(max_length=150, verbose_name="nom de l'entreprise")),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='slug')),
                ('business_registration_number', models.CharField(blank=True, max_length=50, verbose_name="numéro d'immatriculation (RCCM/NIU)")),
                ('identity_number', models.CharField(blank=True, help_text='Numéro de CNI, Passeport ou Récépissé.', max_length=50, verbose_name="numéro de pièce d'identité")),
                ('identity_document', models.FileField(blank=True, help_text="Scan ou photo de la pièce d'identité (PDF, JPG, PNG).", null=True, upload_to='producers/identity_documents/', verbose_name="document d'identité")),
                ('description', models.TextField(blank=True, verbose_name="présentation de l'activité")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'examen")),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_producers', to=settings.AUTH_USER_MODEL, verbose_name='examiné par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.OneToOneField(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil producteur',
                'verbose_name_plural': 'profils producteurs',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text="Indique si l'enregistrement est désactivé sans être supprimé de la BDD.", verbose_name='Supprimé ?')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', "Vérification de l'email"), ('PASSWORD_RESET', 'Réinitialisation du mot de passe')], default='EMAIL_VERIFICATION', max_length=20, verbose_name='objectif')),
                ('expires_at', models.DateTimeField(verbose_name="date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='utilisé')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='users_otpco_user_id_1d4b02_idx')],
            },
        ),
    ]
